---
- hosts: 192.168.2.5
  become: true
  tasks:

    - name: install httpd
      dnf:
        name: httpd
        state: present

    - name: install support for php
      dnf:
        name: php
        state: present
