---
- hosts: 192.168.2.6
  become: true
  tasks:

    - name: install httpd
      package:
        name:
          - httpd
          - telnet
          - php
        state: present
    - name: enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
