---
- hosts: all
  become: true
  tasks:

    - name: install httpd
      package:
        name:
          - httpd
          - telnet
          - php
        state: absent
    - name: enable httpd
      tags: start_httpd
      service:
        name: httpd
        state: started
        enabled: yes
